---
- name: update hosts files
  tags: setup
  hosts: all
  become: true

  tasks:
    - name: Copy hosts
      copy:
        src: etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644


- name: Copy tracking and streaming code on observer
  tags: setup
  hosts: observer
  # TODO: update to copy changes made to the student's files

  tasks:
  - name: Create synch folder
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - '/home/pi/camera/config'
      - '/home/pi/camera/core'
      - '/home/pi/camera/server'
      - '/home/pi/camera/server/templates'
      - '/home/pi/camera/tools'
      - '/home/pi/logs'
      - '/home/pi/media/video'
      - '/home/pi/media/trajectories'
  - name: Copy setup.py
    copy:
      src: setup.py
      dest: /home/pi/
      owner: pi
      group: pi
      mode: 0644
  - name: Copy config
    copy:
      src: "{{ item }}"
      dest: /home/pi/camera/config
      owner: pi
      group: pi
      mode: 0644
    with_items:
      - camera/config/default.yml
  - name: Copy core Python scripts
    copy:
      src: "{{ item }}"
      dest: /home/pi/camera/core
      owner: pi
      group: pi
      mode: 0644
    with_fileglob: camera/core/*.py
  - name: Copy infodynamics
    copy:
      src: camera/core/infodynamics.jar
      dest: /home/pi/camera/core
      owner: pi
      group: pi
      mode: 0644
  - name: Copy Flask Python code
    copy:
      src: "{{ item }}"
      dest: /home/pi/camera/server
      owner: pi
      group: pi
      mode: 0644
    with_items:
      - camera/server/__init__.py
      - camera/server/server.py
      - camera/server/video.py
  - name: Copy Flask templates
    copy:
      src: "{{ item }}"
      dest: /home/pi/camera/server/templates
      owner: pi
      group: pi
      mode: 0644
    with_fileglob: camera/server/templates/*.html
  - name: Copy utils
    copy:
      src: "{{ item }}"
      dest: /home/pi/camera/tools
      owner: pi
      group: pi
      mode: 0644
    with_items:
      - camera/tools/__init__.py
      - camera/tools/colour.py
      - camera/tools/config.py


- name: Service config files for observer
  tags: setup
  hosts: observer
  become: true

  tasks:

    - name: Copy systemd service
      copy:
        src: lib/systemd/system/synch-live-observer-server.service
        dest: /lib/systemd/system/synch-live-observer-server.service
        owner: root
        group: root
        mode: 0644
    - name: Copy avahi service
      copy:
        src: etc/avahi/services/synch-live-observer.service
        dest: /etc/avahi/services/synch-live-observer.service
        owner: root
        group: root
        mode: 0644
    - name: Reload systemd to pick up changes
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: Start service
      ansible.builtin.systemd:
        name: synch-live-observer-server 
        state: restarted
      become: yes


- name: Copy LED control code on all players
  tags: setup
  hosts: players

  tasks:

  - name: Create synch folder
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - '/home/pi/synch-live'
      - '/home/pi/synch-live/leds'
      - '/home/pi/synch-live/leds/server'
      - '/home/pi/synch-live/leds/server/templates'
      - '/home/pi/synch-live/leds/server/static'
      - '/home/pi/synch-live/logs'
  - name: Copy LED light control Python scripts
    copy:
      src: "{{ item }}"
      dest: /home/pi/synch-live/leds
      owner: pi
      group: pi
      mode: 0644
    with_fileglob: leds/*.py
  - name: Copy server code
    copy:
      src: "{{ item }}"
      dest: /home/pi/synch-live/leds/server
      owner: pi
      group: pi
      mode: 0644
    with_fileglob: leds/server/*.py
  - name: Copy server template code
    copy:
      src: "{{ item }}"
      dest: /home/pi/synch-live/leds/server/templates
      owner: pi
      group: pi
      mode: 0644
    with_fileglob: leds/server/templates/*.html
  - name: Copy server static code
    copy:
      src: "{{ item }}"
      dest: /home/pi/synch-live/leds/server/static
      owner: pi
      group: pi
      mode: 0644
    with_fileglob: leds/server/static/*



- name: Service config files for players
  tags: setup
  hosts: players
  become: true

  tasks:

    - name: Copy systemd service
      copy:
        src: lib/systemd/system/synch-live-player-server.service
        dest: /lib/systemd/system/synch-live-player-server.service
        owner: root
        group: root
        mode: 0644
    - name: Copy avahi service
      copy:
        src: etc/avahi/services/synch-live-player.service
        dest: /etc/avahi/services/synch-live-player.service
        owner: root
        group: root
        mode: 0644
    - name: Reload systemd to pick up changes
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: Start service
      ansible.builtin.systemd:
        name: synch-live-player-server 
        state: restarted
      become: yes

