---
- name: Stop startup loop
  tags: test, pilot, breathe, rainbow, exposure, stop
  hosts: players
  tasks:
  - name: stop startup
    become: true
    shell:
      cmd: "pkill -f startup"
    ignore_errors: true
  - name: stop waitloop
    become: true
    shell:
      cmd: "pkill -f wait"
    ignore_errors: true

- name: Turn on pilot
  tags: test, pilot
  hosts: players
  tasks:
  - name: Turn on pilot
    shell:
      cmd: python3 -m leds.wait pilot
      chdir: /home/pi/

- name: Run breathing
  tags: test, breathe
  hosts: players
  tasks:
  - name: Run breathing
    shell:
      cmd: python3 -m leds.wait breathe
      chdir: /home/pi/

- name: Run rainbow
  tags: test, rainbow
  hosts: players
  tasks:
  - name: Run rainbow
    shell:
      cmd: python3 -m leds.wait rainbow
      chdir: /home/pi/

- name: Turn on experimental lights and keep on to calibrate exposure
  tags: test, exposure
  hosts: players
  tasks:
  - name: Run exposure
    shell:
      cmd: python3 -m leds.wait exposure
      chdir: /home/pi/


- name: Run mock loop example
  tags: test, schedule
  hosts: players
  tasks:
  - name: Add cron job
    cron:
      name: "synch-loop-test-{{ MINUTE }}"
      minute: "{{ MINUTE }}"
      job: 'while [ "10" -gt "$(date +\%S)" ]; do /bin/sleep 0.1; done; python3 -m leds.mockloop'


- name: Stop lights
  tags: test, stop
  hosts: players
  tasks:

  - name: Turn off leds
    shell: "python3 -m leds.stop"

  - name: Turn on pilot
    shell: "python3 -m leds.wait pilot"

  - name: Delete cron job
    cron:
      name: "synch-loop-test-{{ MINUTE }}"
      minute: "{{ MINUTE }}"
      state: absent
      ignore_errors: yes

